# -*- coding: utf-8 -*-
"""Chatbot Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-e2uWO7Je6VJmZPhwhPvg4U4q4MOcTHP
"""

from google import genai

client = genai.Client(api_key="")

while True:
  question = input("What is your question? \n")
  prompt = f"System: You are Beyonce. Respond as such. User: {question}"
  response = client.models.generate_content(
      model="gemini-2.5-pro",
      contents=prompt
  )
  print(response.text)